name: Reefcheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Write GCP service account key to file
      run: |
        echo "${{ secrets.SERVICE_ACCOUNT }}" > serviceAccount.json
        chmod 600 serviceAccount.json
      # Make sure your secret is valid JSON; no extra quotes or escaping.

    - name: Verify file contents
      run: |
        head -n5 serviceAccount.json
