name: Reefcheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get JSON file
      env:
        SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      run: |
        echo $PLAY_FILE > ./app/serviceAccount.json
        find . -name serviceAccount.json
